/*
 * timer_cfg.h
 *
 *  Created on: Oct 24, 2023
 *      Author: Ahmed Dwidar
 */

#ifndef MCAL_TIMER_CFG_H_
#define MCAL_TIMER_CFG_H_

#include"timer.h"

/*
 * timer prescaler
TIMER_NO_CLOCK
TIMER_NO_PRESCALER
TIMER_WITH_PRESCALER_8
TIMER_WITH_PRESCALER_64
TIMER_WITH_PRESCALER_256
TIMER_WITH_PRESCALER_1024
TIMER_WITH_EX_CLOCK_FALLING
TIMER_WITH_EX_CLOCK_RISING
*/
#define TIMER_SELECT_PRESCALER                                TIMER_WITH_PRESCALER_8

/*
 * Waveform Generation Mode Bit Description
TIMER_NORMAL_MODE
TIMER_PWM_PHASE_CORRECT_MODE
TIMER_COMPARE_MATCH_MODE
TIMER_NORMAL_PWM_FAST_MODE
*/
#define TIMER_WAVEFORM_GENERATION_MODE                        TIMER_COMPARE_MATCH_MODE

/*
 * Compare Output Mode with or without pwm
TIMER_COMPARE_MODE_NONE_PWM
TIMER_COMPARE_MODE_WITH_PWM
*/
#define TIMER_COMPARE_MODE_WITH_OR_WITHOUT_PWM                TIMER_COMPARE_MODE_NONE_PWM

/*
 * Compare Output Mode with pwm
TIMER_COMPARE_MODE_PWM_FAST
TIMER_COMPARE_MODE_PWM_PHASE_CORRECT

*/
#if(TIMER_COMPARE_MODE_WITH_OR_WITHOUT_PWM == TIMER_COMPARE_MODE_WITH_PWM)
#define TIMER_COMPARE_MODE_WITH_PWM_FAST_OR_PHASE_CORRECT     TIMER_COMPARE_MODE_PWM_FAST

   #if(TIMER_WAVEFORM_GENERATION_MODE == TIMER_COMPARE_MATCH_MODE)
       #if(TIMER_COMPARE_MODE_WITH_OR_WITHOUT_PWM == TIMER_COMPARE_MODE_WITH_PWM)
               #if(TIMER_COMPARE_MODE_WITH_PWM_FAST_OR_PHASE_CORRECT == TIMER_COMPARE_MODE_PWM_FAST)

/*
 *Compare Output Mode, Fast PWM Mode
TIMER_NORMAL_WITH_FAST_PWM
TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_NON_INVERTING_WITH_FAST_PWM
TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_INVERTING_WITH_FAST_PWM
*/

#define TIMER_COMPARE_MODE_WITH_FAST_PWM                  TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_NON_INVERTING_WITH_FAST_PWM

#elif(TIMER_COMPARE_MODE_WITH_PWM_FAST_OR_PHASE_CORRECT == TIMER_COMPARE_MODE_PWM_PHASE_CORRECT)

/*
 *Compare Output Mode, Phase Correct PWM Mode
TIMER_NORMAL_WITH_PHASE_CORRECT_PWM
TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_NON_INVERTING_WITH_PHASE_CORRECT_PWM
TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_EITH_INVERTING_WITH_PHASE_CORRECT_PWM
*/
#define TIMER_COMPARE_MODE_WITH_PHASE_CORRCT_PWM          TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_NON_INVERTING_WITH_PHASE_CORRECT_PWM

               #endif
        #endif
   #endif
#endif
/*
 * Compare Output Mode, non-PWM Mode
TIMER_NORMAL_NONE_PWM
TIMER_TOGGLE_OC_REG_IN_COMPARE_MODE_NONE_PWM
TIMER_CLEAR_OC_REG_IN_COMPARE_MODE_NONE_PWM
TIMER_SET_OC_REG_IN_COMPARE_MODE_NONE_PWM
*/
#define TIMER_COMPARE_MODE_WITHOUT_PWM                    TIMER_NORMAL_NONE_PWM

/*
 * timer frequency
MAX_FREQUENCY
MID_FREQUENCY
MIN_FREQUENCY
*/
#define MICROCONTROLLER_FREQUUENCE                        MID_FREQUENCY

/*
 * timer selection
TIMER_ZERO
TIMER_ONE
TIMER_TWO
*/
#define TIMER_SELECT                                      TIMER_ZERO


/*icu in timer1 clock types
ICU_FALLING_EDGE
ICU_RISING_EDGE
*/
#define ICU_CLOCK_TYPE                                    ICU_PRESCALER_F_CPU_8

/*icu in timer1 clock types
ICU_PRESCALER_NO_CLOCK
ICU_PRESCALER_F_CPU_CLOCK
ICU_PRESCALER_F_CPU_8
ICU_PRESCALER_F_CPU_64
ICU_PRESCALER_F_CPU_256
ICU_PRESCALER_F_CPU_1024
*/
#define ICU_EDGE_TYPE                                     ICU_RISING_EDGE


#endif /* MCAL_TIMER_CFG_H_ */
