/*
 * ADC_cfg.h
 *
 *  Created on: Oct 23, 2023
 *      Author: Ahmed Dwidar
 */

#ifndef MCAL_ADC_CFG_H_
#define MCAL_ADC_CFG_H_

/*
AREF_VOLTAGE
AVCC_VOLTAGE
INTERNAL_VOLTAGE
*/
#define ADC_REF_VOLT_VALUE          AVCC_VOLTAGE
/*
ADC_PIN0
ADC_PIN1
ADC_PIN2
ADC_PIN3
ADC_PIN4
ADC_PIN5
ADC_PIN6
ADC_PIN7
*/
#define ADC_SELECT_PIN_TO_READ        ADC_PIN0

/*
BIT_NU0
BIT_NU1
BIT_NU2
BIT_NU3
BIT_NU4
BIT_NU5
BIT_NU6
BIT_NU7
*/
#define ADLAR        BIT_NU5
#define ADEN         BIT_NU7
#define ADSC         BIT_NU6
#define ADATE        BIT_NU5
#define ADIF         BIT_NU4
#define ADIE         BIT_NU3

/*
MAX_FREQUENCY
MID_FREQUENCY
MIN_FREQUENCY
*/
#define MICROCONTROLLER_FREQUUENCE     MIN_FREQUENCY

/*
ADC_PRESC_2
ADC_PRESC_4
ADC_PRESC_8
ADC_PRESC_16
ADC_PRESC_32
ADC_PRESC_64
ADC_PRESC_128
*/
#if(MICROCONTROLLER_FREQUUENCE == 16000000)
#define ADC_SELECT_PRESCALER                         ADC_PRESC_128

#elif(MICROCONTROLLER_FREQUUENCE == 8000000)
#define ADC_SELECT_PRESCALER                         ADC_PRESC_64

#elif(MICROCONTROLLER_FREQUUENCE == 1000000)
#define ADC_SELECT_PRESCALER                         ADC_PRESC_8
#endif

#endif /* MCAL_ADC_CFG_H_ */
